[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  DATABASE_URL = "postgresql://postgres:JTEXUJtjen1HnTkN@db.dnlkdtktlqendhaqcnua.supabase.co:5432/postgres"
